# Generated by Django 5.2 on 2025-06-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_studentclass_remove_student_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree_completed',
            field=models.BooleanField(default=False),
        ),
    ]
