# Generated by Django 5.2 on 2025-06-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_degree_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='approval_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
